language: node_js
node_js:
    - '7'
cache:
    directories:
        - 'node_modules'
deploy:
    provider: npm
    email: 'stephenwpoole@gmail.com'
    api_key: $NPM_API_KEY
    on:
        tags: true
        branch: master
script:
    - npm install codecov -g
    - npm install
    - npm test
    - npm start
after_success:
    - nyc report --reporter=json > coverage/coverage.json && codecov --token=$CODECOV_TOKEN
